feat: add support for extra volumes and extra volume mounts
chartmuseum/charts pull request #28
Opened 2021-11-04 17:04 UTC by eddycharly

This PR adds support for extra volumes and extra volume mounts.

This is useful to enable IRSA on AWS without pod identity webhook as it requires an extra volume, an extra volume mount and env variables to be set so that aws sdk can make use of `AssumeRoleWithWebIdentity`.

2021-11-04 22:35 UTC, eddycharly commented
cc @jdolitsky

2021-11-22 22:50 UTC, eddycharly commented
@jdolitsky anything I can do to make this move forward ?

2021-11-22 22:57 UTC, jdolitsky requested changes
Can you please add these new values to README, and bump chart version to `3.4.0`?

2021-11-22 23:01 UTC, eddycharly commented
Sure, I’ll do that tomorrow !
Thanks for your comments :)

2021-11-23 08:17 UTC, eddycharly commented
@jdolitsky I made the requested changes.

2021-11-23 20:21 UTC, jdolitsky approved these changes

2021-11-23 20:21 UTC, merged