Support defining scheme of liveness and readiness checks
chartmuseum/charts pull request #32
Opened 2021-12-23 10:34 UTC by vespian

This PR adds support for setting the scheme of readiness and liveliness checks.

In our use-case we can't use ingress rules for TLS as we use chartmuseum to host helm charts during bootstrap and  also need chartmuseum itself to use TLS as we want to enable authz for API endpoints that allow updating/uploading charts. User/pass should never be transmitted in plaintext even between ingress and the pod.

I could add TLS support with help `extraVolumes`, `extraVolumeMounts` and `extraArgs` but ATM there is no way to adjust liveness and readiness checks to support TLS connection to chartmuseum. This PR fixes that.

2022-01-22 09:53 UTC, mkilchhofer commented
Relates / duplicates https://github.com/chartmuseum/charts/pull/17

2022-01-30 14:58 UTC, cbuto requested changes
lgtm, can you bump the chart version to `3.5.0` @vespian? 🙌

cc @jdolitsky

2022-01-31 16:18 UTC, cbuto approved these changes

2022-01-31 16:20 UTC, tiagoposse commented
for whatever is worth, as the author of #17, I think this PR is superior.

2022-01-31 23:19 UTC, jdolitsky approved these changes

2022-01-31 23:19 UTC, merged